### ISSUE TITLE
Slider Rendering issue

### ISSUE THREAD

**Issue by sunbliss** [null2/skidder#1]
Hi @null2 

I am using your slider code for a photography website. 
I am facing a problem with "jquery.skidder.js". 

The slider renders as expected when I am using `<script src="http://www.jqueryscript.net/demo/Auto-Scalable-Responsive-Image-Carousel-Plugin-For-jQuery-skidder/src/jquery.skidder.js"></script>`

When I am using `<script src="{{ site.baseurl }}/js/jquery.skidder.js"></script>` the slider will not render as expected.

Would you mind helping me find and correct the mistake I made in my template code?

[ATHENEE](https://github.com/sunbliss/athenee)

Thank you.

**Comment by LinzardMac** [comment]
Did you verify that you uploaded the js file to the /js/ folder on your server and that the base.url is outputting the proper url

**Comment by sunbliss** [comment]
@Lindsayanng The slider works fine now, thank you!
I had missed this step. 
You can see skidder in action here: [ATHENEE](http://sunbliss.github.io/athenne/)
Thank you for your help and the excellent code. :+1:
